services:
  - type: web
    name: rare-oddities-backend
    env: java
    rootDir: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SPRING_DATASOURCE_URL
        value: YOUR_DB_URL
      - key: SPRING_DATASOURCE_USERNAME
        value: YOUR_DB_USERNAME
      - key: SPRING_DATASOURCE_PASSWORD
        value: YOUR_DB_PASSWORD
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: com.mysql.cj.jdbc.Driver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
